name: Google Api
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add content to log
        run: |
          echo "Test" >> log.txt
      
      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git add .
          git commit -m "Updating the repository GitHub html pages in the docs folder"

      - name: Push changes  
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
